# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d301ce44192a9a5e50f72b6f435ac57e3ed783e91ceb04e6a9ec73f2be0667bb748fbdb23cf8cd55a01e15bc55abb324325a55ec4ba44e2997cb6ee88f41237f

test:
  secret_key_base: 2aef136f80193086d2703cbbcc9dc0b5806d50270a7d1c68c5704c8c312a9919c9b6542e70d2970a1c89284afdb51d6a6d8ee00b952deef0082b0d73eb14a669

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
